# Generated by Django 5.0.4 on 2024-05-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecommerce_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Desicription', models.CharField(blank=True, max_length=100, null=True)),
                ('C_image', models.ImageField(blank=True, null=True, upload_to='C_image')),
            ],
        ),
    ]
