# Generated by Django 5.0.4 on 2024-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=200, null=True)),
                ('P_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('P_price', models.IntegerField(blank=True, null=True)),
                ('Desicription', models.CharField(blank=True, max_length=100, null=True)),
                ('P_image', models.ImageField(blank=True, null=True, upload_to='P_image')),
            ],
        ),
    ]
