# Generated by Django 5.0.4 on 2024-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_register_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='Confirm_password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
