# Generated by Django 5.0.4 on 2024-06-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0003_register_db_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_db',
            name='Confirm_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register_db',
            name='Password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
