# Generated by Django 5.0.4 on 2024-06-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0006_cartdb_delete_sign_indb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_db',
            old_name='Name',
            new_name='UserName',
        ),
    ]
