# Generated by Django 5.0.4 on 2024-06-05 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0007_rename_name_register_db_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Email',
            new_name='UserName',
        ),
    ]
