# Generated by Django 5.0.4 on 2024-06-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0009_rename_username_register_db_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='UserName',
            new_name='Username',
        ),
    ]
