# Generated by Django 5.0.4 on 2024-06-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0010_rename_username_cartdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
