# Generated by Django 5.0.4 on 2024-06-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0011_alter_cartdb_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Username',
            new_name='username',
        ),
    ]
