# Generated by Django 5.0.4 on 2024-06-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0013_rename_totalprice_cartdb_totalprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='Username',
            new_name='username',
        ),
    ]
